# Generated by Django 5.1.3 on 2024-11-15 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered',
            field=models.ManyToManyField(related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
