# Generated by Django 5.1.3 on 2024-11-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tournament_current_round_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament', 'date']},
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('participant1_score', models.IntegerField()),
                ('participant2_score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
