# Generated by Django 5.1.3 on 2024-11-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_match_options_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='participant1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='participant2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
